// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCklSzUWtVv-_3-1sOKgfLvoLV4P8g90lo',
    appId: '1:56567342657:web:8885cdf04f79cfc0b6c8c0',
    messagingSenderId: '56567342657',
    projectId: 'projeto-teste-b0c1b',
    authDomain: 'projeto-teste-b0c1b.firebaseapp.com',
    storageBucket: 'projeto-teste-b0c1b.firebasestorage.app',
    measurementId: 'G-XFPP85Y0RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3BkP_5AiIWS1AjlZfALmlJWxOz1DzIWk',
    appId: '1:56567342657:android:b05e0a0e433d28eab6c8c0',
    messagingSenderId: '56567342657',
    projectId: 'projeto-teste-b0c1b',
    storageBucket: 'projeto-teste-b0c1b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCklSzUWtVv-_3-1sOKgfLvoLV4P8g90lo',
    appId: '1:56567342657:web:7ad66c662ae02ab5b6c8c0',
    messagingSenderId: '56567342657',
    projectId: 'projeto-teste-b0c1b',
    authDomain: 'projeto-teste-b0c1b.firebaseapp.com',
    storageBucket: 'projeto-teste-b0c1b.firebasestorage.app',
    measurementId: 'G-B0VSDCSFPL',
  );
}
